### PR TITLE
Add cn to new be list

### PR DESCRIPTION
**Pull request by JasonP01**

### CODE REVIEW

**Comment by JasonP01** [comment]
First pr lets go 🗣️ 🔥

**Comment by Anuken** [comment]
I literally just removed this server, it's v146.

**Comment by JasonP01** [comment]
> I literally just removed this server, it's v146.

No its not, thats the testing server, its a BE server they are just testing something on 146. It was on the old be list!

**Comment by Anuken** [comment]
> No its not

image

It's clearly v146, and I can't connect to it, because the netcode is different.

If they are "just testing something on 146", it should not be on the *BE server list*!

> It was on the old be list!

And as I said above, I just removed it.

**Comment by phinner** [comment]
:skull: Json, what have you done!

**Comment by JasonP01** [comment]
> 💀 Json, what have you done!

I just tried to add cn testing back 💀 its not my fault someone decided to change its version

**Pull request closed without merging**
